version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8081:8081"
    networks:
      - studentapp-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    networks:
      - studentapp-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - studentapp-network

networks:
  studentapp-network:
    driver: bridge
