version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8081:8081"
    networks:
      - studentapp-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - studentapp-network
    depends_on:
      - backend

networks:
  studentapp-network:
    driver: bridge

